### ISSUE TITLE
Could you please give the package name of AIRCODE in NPM to my company？

### ISSUE THREAD

**Issue by wangxiao** [DevBash1/Aircode#1]
Our company's product is https://aircode.io , and there is no such package name at present. Could you please give the package name of AIRCODE in NPM to my company？

**Comment by DevBash1** [comment]
> Our company's product is https://aircode.io , and there is no such package name at present. Could you please give the package name of AIRCODE in NPM to my company？

Send me an email let's talk.
ikorosamuel1@gmail.com
